# Etapa 1: Compilación de la aplicación Angular
FROM node:22-alpine3.19 as build

# Establece el directorio de trabajo
WORKDIR /usr/src/app

# Copia los archivos de dependencias
COPY package.json package-lock.json ./

# Instala las dependencias de la aplicación
RUN npm install --legacy-peer-deps --force

# Copia el código fuente de la aplicación
COPY . .

# Compila la aplicación Angular para Prod
RUN npm run build --prod

# Etapa 2: Imagen final para servir la aplicación
FROM nginx:latest as production

# Copia los archivos compilados desde la etapa de compilación
COPY --from=build /usr/src/app/dist/fuse /usr/share/nginx/html
COPY /nginx.conf /etc/nginx/conf.d/default.conf

# Exponer el puerto 80 para el tráfico HTTP
EXPOSE 80

# Comando para iniciar Nginx
CMD ["nginx", "-g", "daemon off;"]
