FROM node:20-alpine

# Directorio de trabajo
WORKDIR /usr/src/app

# Instalar dependencias del sistema necesarias para Prisma  
RUN apk add --no-cache openssl libssl3  

# Copia los archivos de dependencias
COPY package.json package-lock.json ./

# Copiar la carpeta prisma
COPY prisma ./prisma  

# Copiar las variables de entorno
COPY .env ./

# Instala dependencias del proyecto
RUN npm install

# Instala ts-node-dev globalmente
RUN npm install -g ts-node-dev

# Copia el resto del código del proyecto
COPY . .

# Genera el cliente de Prisma
RUN npx prisma generate

# Expone el puerto 5000 para la app
EXPOSE 5000

# Ejecuta la app en modo desarrollo con recarga automática
CMD ["ts-node-dev", "--respawn", "--transpile-only", "--poll", "src/main.ts"]
