FROM node:20-alpine

# Establece el directorio de trabajo
WORKDIR /usr/src/app

# Copia los archivos de dependencias
COPY package.json package-lock.json ./

# Instala dependencias del proyecto
RUN npm install

# Instala ts-node-dev globalmente
RUN npm install -g ts-node-dev

# Copia el resto del código del proyecto
COPY . .

# Expone el puerto 5000 para la aplicación
EXPOSE 5000

# Ejecuta la app en modo desarrollo con recarga automática
CMD ["ts-node-dev", "--respawn", "--transpile-only", "--poll", "src/main.ts"]
