name: Deploy Backend to AWS Lightsail (kitchen-ms)

on:
  push:
    branches: ["main"]
    paths:
      - "backend/microservices/kitchen/**"
      - ".github/workflows/kitchen-ms-deploy.yml"
  merge_group:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_SERVER_SSH_KEY  }}

      - name: Build Docker image
        run: |
          docker build -t kitchen-ms \
            --build-arg PORT=${{ secrets.PORT }} \
            --build-arg RABBITMQ_URL=${{ secrets.RABBITMQ_URL }} \
            --build-arg DATABASE_URL=${{ secrets.KITCHEN_DATABASE_URL }} \
            -f backend/microservices/kitchen/dockerfile.prod backend/microservices/kitchen

      - name: Save Docker image to tar
        run: |
          docker save kitchen-ms -o kitchen-ms.tar

      - name: Copy Docker image to Lightsail
        run: |
          scp -o StrictHostKeyChecking=no kitchen-ms.tar ubuntu@${{ secrets.AWS_SERVER_IP}}:/home/ubuntu/backend-images

      - name: Load Docker image on Lightsail
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.AWS_SERVER_IP}} '
            cd /home/ubuntu/backend-images &&
            sudo docker load -i kitchen-ms.tar
          '

      - name: Deploy container on Lightsail
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.AWS_SERVER_IP}} '
            docker stop kitchen-ms 2>/dev/null || true &&
            docker rm kitchen-ms 2>/dev/null || true &&
            docker run -d --name kitchen-ms --network backend-network --network-alias kitchen-ms kitchen-ms
          '
